Open-Transactions/Moneychanger

project/common.pri, project/moneychanger-qt/moneychanger-qt.pro, src/core/handlers/contacthandler.cpp, src/core/handlers/contacthandler.hpp, src/core/moneychanger.cpp, src/gui/ui/dlgencrypt.cpp, src/gui/ui/dlgmarkets.cpp, src/gui/widgets/compose.cpp, src/gui/widgets/credentials.cpp, src/gui/widgets/homedetail.cpp, src/gui/widgets/requestdlg.cpp, src/gui/widgets/senddlg.cpp
=> Some fixes due to changes in opentxs.

src/core/handlers/contacthandler.cpp, src/gui/widgets/assetdetails.cpp, src/gui/widgets/pageacct_nym.cpp, src/gui/widgets/pageaddcontract.cpp, src/gui/widgets/pageaddcontract.hpp, src/gui/widgets/pageaddcontract.ui, src/gui/widgets/pagecreatecontract.cpp, src/gui/widgets/pagecreatecontract.hpp, src/gui/widgets/pagecreatecontract.ui, src/gui/widgets/requestdlg.ui, src/gui/widgets/serverdetails.cpp
=> "new server contract" and "new asset contract".

src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/gui.pri, src/gui/ui/dlglog.cpp, src/gui/ui/dlglog.hpp, src/gui/ui/dlglog.ui, src/gui/ui/dlgmarkets.cpp, src/gui/widgets/accountdetails.cpp, src/gui/widgets/cashpurse.cpp, src/gui/widgets/compose.cpp, src/gui/widgets/homedetail.cpp, src/gui/widgets/marketdetails.cpp, src/gui/widgets/offerdetails.cpp, src/gui/widgets/requestdlg.cpp, src/gui/widgets/senddlg.cpp
=> Fixed "cursor spinning" bug when server is down.

src/core/moneychanger.cpp
Fixed default checkmarks; added "signer" to asset GUI.
=> Fixed default checkmarks; added "signer" to asset

src/core/moneychanger.cpp, src/gui/widgets/assetdetails.cpp, src/gui/widgets/assetdetails.hpp, src/gui/widgets/assetdetails.ui, src/gui/widgets/detailedit.cpp, src/gui/widgets/home.cpp
=> Added "Signer Nym" to asset details page.

src/core/moneychanger.cpp, src/gui/widgets/accountdetails.ui, src/gui/widgets/assetdetails.cpp, src/gui/widgets/assetdetails.hpp, src/gui/widgets/assetdetails.ui, src/gui/widgets/compose.ui, src/gui/widgets/requestdlg.ui, src/gui/widgets/senddlg.ui, src/gui/widgets/serverdetails.cpp, src/gui/widgets/serverdetails.hpp, src/gui/widgets/serverdetails.ui
buttons for grabbing IDs from some details screens
=> Added "issue asset" to the GUI. Also added copy

README.md
=> Updated README.md to fix instructions.

src/core/handlers/DBHandler.cpp, src/core/handlers/DBHandler.hpp, src/core/handlers/contacthandler.cpp, src/core/handlers/contacthandler.hpp, src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/gui.pri, src/gui/ui/dlgcreatepassphrase.cpp, src/gui/ui/dlgcreatepassphrase.hpp, src/gui/ui/dlgcreatepassphrase.ui, src/gui/ui/dlgpassphrasemanager.cpp, src/gui/ui/dlgpassphrasemanager.hpp, src/gui/ui/dlgpassphrasemanager.ui, src/gui/widgets/agreementdetails.cpp, src/gui/widgets/offerdetails.ui, src/namecoin/Namecoin.cpp
=> Added password manager feature to Moneychanger.

src/gui/ui/dlgcreatepassphrase.cpp, src/gui/ui/dlgcreatepassphrase.hpp, src/gui/ui/dlgcreatepassphrase.ui, src/gui/ui/dlgpassphrasemanager.cpp, src/gui/ui/dlgpassphrasemanager.hpp, src/gui/ui/dlgpassphrasemanager.ui
=> Passphrase Manager dialog.

src/core/core.pri, src/core/handlers/focuser.cpp, src/core/handlers/focuser.h, src/core/handlers/focuser.mm, src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/rpc/mcrpcservice.cpp
Add the ability to focus the send dialog window on open
=> Focuser Class

src/core/applicationmc.cpp, src/core/moneychanger.cpp, src/gui/ui/dlgdecrypt.cpp, src/gui/ui/dlgencrypt.cpp, src/gui/ui/dlglog.cpp, src/gui/ui/dlgmarkets.cpp, src/gui/ui/dlgmenu.cpp, src/gui/ui/dlgpassphrasemanager.cpp, src/gui/widgets/btcpoolmanager.cpp, src/gui/widgets/btcsenddlg.cpp, src/gui/widgets/btctransactionmanager.cpp, src/gui/widgets/contactdetails.cpp, src/gui/widgets/detailedit.cpp, src/gui/widgets/home.cpp, src/gui/widgets/homedetail.cpp, src/gui/widgets/requestdlg.cpp, src/gui/widgets/senddlg.cpp
=> Added focuser all over the place.

src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/widgets/editdetails.cpp, src/gui/widgets/home.cpp, src/gui/widgets/home.hpp, src/gui/widgets/homedetail.cpp, src/gui/widgets/homedetail.hpp
=> Updates to main menu and overview page.

src/gui/widgets/assetdetails.cpp, src/gui/widgets/compose.cpp, src/gui/widgets/compose.hpp, src/gui/widgets/contactdetails.cpp, src/gui/widgets/home.cpp, src/gui/widgets/nymdetails.cpp, src/gui/widgets/nymdetails.hpp, src/gui/widgets/nymdetails.ui, src/gui/widgets/serverdetails.cpp
=> Added some long-overdue improvements to the GUI.

src/core/moneychanger.cpp
=> Auto-create a contact whenever creating a new Nym.

src/core/core.pri, src/core/handlers/DBHandler.cpp, src/core/handlers/DBHandler.hpp, src/core/handlers/contacthandler.cpp, src/core/handlers/contacthandler.hpp, src/core/handlers/modeltradearchive.cpp, src/core/handlers/modeltradearchive.hpp, src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/gui.pri, src/gui/ui/dlgmenu.cpp, src/gui/ui/dlgmenu.hpp, src/gui/ui/dlgmenu.ui, src/gui/ui/dlgtradearchive.cpp, src/gui/ui/dlgtradearchive.hpp, src/gui/ui/dlgtradearchive.ui, src/gui/ui/messages.cpp, src/gui/ui/messages.hpp, src/gui/ui/messages.ui, src/gui/widgets/home.cpp, src/gui/widgets/home.hpp, src/gui/widgets/offerdetails.cpp, src/gui/widgets/offerdetails.hpp, src/gui/widgets/offerdetails.ui, src/gui/widgets/requestdlg.cpp, src/gui/widgets/senddlg.cpp
=> Added market trading receipt archive.

src/core/handlers/DBHandler.cpp, src/core/handlers/contacthandler.cpp, src/core/handlers/contacthandler.hpp, src/core/handlers/modelmessages.cpp, src/gui/ui/dlgtradearchive.cpp, src/gui/ui/messages.cpp, src/gui/ui/messages.hpp, src/gui/ui/messages.ui, src/gui/widgets/homedetail.cpp
=> Finished right-click menu for Messages tableView.

src/core/handlers/modelpayments.cpp, src/core/handlers/modelpayments.hpp, src/gui/ui/payments.cpp, src/gui/ui/payments.hpp, src/gui/ui/payments.ui, src/rpc/mcrpcservice.cpp, src/rpc/mcrpcservice.h
=> Fixes for Faiz.

src/core/moneychanger.cpp, src/gui/widgets/nymdetails.cpp, src/rpc/mcrpcservice.cpp, src/rpc/mcrpcservice.h
Update for API change in opentxs #639.
=> update API for alt_location -> description change

doc/INSTALL-unix.txt, doc/ubuntu.md, src/core/handlers/contacthandler.cpp, src/core/handlers/modelpayments.cpp
=> Added ubuntu.md from drgorb.

src/core/handlers/contacthandler.cpp, src/core/handlers/contacthandler.hpp, src/core/handlers/modelmessages.hpp, src/core/handlers/modelpayments.cpp, src/core/handlers/modelpayments.hpp, src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/ui/dlgexportcash.cpp, src/gui/ui/dlgexportedcash.cpp, src/gui/ui/dlgexportedcash.hpp, src/gui/ui/dlgexportedcash.ui, src/gui/ui/dlgexportedtopass.hpp, src/gui/ui/payments.cpp, src/gui/ui/payments.hpp, src/gui/ui/payments.ui, src/gui/widgets/accountdetails.cpp, src/gui/widgets/accountdetails.hpp, src/gui/widgets/accountdetails.ui, src/gui/widgets/compose.cpp, src/gui/widgets/contactdetails.cpp, src/gui/widgets/contactdetails.hpp, src/gui/widgets/contactdetails.ui, src/gui/widgets/detailedit.ui, src/gui/widgets/homedetail.cpp, src/gui/widgets/requestdlg.cpp, src/gui/widgets/requestdlg.ui, src/gui/widgets/senddlg.cpp, src/gui/widgets/senddlg.hpp, src/gui/widgets/senddlg.ui
=> Many more UI updates. Make sure you grab latest OT

src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/gui.pri, src/gui/ui/dlgmenu.cpp, src/gui/ui/dlgmenu.hpp, src/gui/ui/dlgmenu.ui, src/gui/ui/payments.cpp, src/gui/widgets/accountdetails.cpp, src/gui/widgets/accountdetails.ui, src/gui/widgets/pageacct_asset.cpp, src/gui/widgets/pageacct_nym.cpp, src/gui/widgets/pageacct_server.cpp, src/gui/widgets/pagecreatecontract.cpp, src/gui/widgets/pageoffer_accounts.cpp, src/gui/widgets/pageoffer_assets.cpp, src/gui/widgets/pagesmart_nymacct.cpp, src/gui/widgets/proposeplandlg.cpp, src/gui/widgets/proposeplandlg.hpp, src/gui/widgets/proposeplandlg.ui, src/gui/widgets/requestdlg.cpp, src/gui/widgets/senddlg.cpp, src/gui/widgets/settings.cpp, src/gui/widgets/settings.hpp, src/gui/widgets/settings.ui
New Main navigation window, "Recurring Payments" dialog, + various UI improvements.
=> New windows, UI updates.

src/gui/ui/dlgmenu.ui, src/gui/widgets/contactdetails.cpp, src/gui/widgets/contactdetails.hpp, src/gui/widgets/credentials.cpp, src/gui/widgets/nymdetails.cpp, src/gui/widgets/nymdetails.hpp, src/gui/widgets/proposeplandlg.cpp, src/gui/widgets/proposeplandlg.hpp, src/gui/widgets/proposeplandlg.ui
=> More UI updates. Added Contact Data to Nym+Contact

src/core/handlers/DBHandler.cpp, src/core/handlers/modelpayments.cpp, src/core/moneychanger.cpp, src/gui/widgets/homedetail.cpp, src/gui/widgets/proposeplandlg.cpp
=> More stuff for recurring payments.

src/gui/widgets/homedetail.cpp
=> fixes for some icons.

src/core/handlers/contacthandler.cpp, src/core/handlers/contacthandler.hpp, src/core/handlers/modelclaims.cpp, src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/ui/messages.cpp, src/gui/ui/messages.hpp, src/gui/widgets/contactdetails.cpp, src/gui/widgets/nymdetails.cpp
=> Added "Download Credentials" right-click on msgs.

src/core/core.pri, src/core/handlers/DBHandler.cpp, src/core/handlers/DBHandler.hpp, src/core/handlers/contacthandler.cpp, src/core/handlers/contacthandler.hpp, src/core/handlers/modelverifications.cpp, src/core/handlers/modelverifications.hpp, src/core/mapidname.hpp, src/core/moneychanger.cpp, src/gui/widgets/contactdetails.cpp, src/gui/widgets/detailedit.hpp, src/gui/widgets/nymdetails.cpp, src/gui/widgets/nymdetails.hpp, src/gui/widgets/pagenym_altlocation.cpp, src/gui/widgets/wizardeditprofile.cpp
=> Claim verifications for relationships (WoT).

src/core/handlers/modelverifications.cpp, src/core/handlers/modelverifications.hpp, src/core/mapidname.hpp
=> missing files.

src/core/handlers/contacthandler.cpp, src/core/handlers/modelpayments.hpp, src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/widgets/proposeplandlg.cpp, src/gui/widgets/proposeplandlg.hpp
=> More updates for Payment Plans in UI.

src/core/handlers/modelpayments.cpp, src/core/moneychanger.cpp, src/gui/widgets/homedetail.cpp
=> Updates for recurring payments.

src/core/core.pri, src/core/handlers/DBHandler.cpp, src/core/handlers/DBHandler.hpp, src/core/handlers/contacthandler.cpp, src/core/handlers/contacthandler.hpp, src/core/handlers/modelagreements.cpp, src/core/handlers/modelagreements.hpp, src/core/handlers/modelpayments.hpp, src/core/handlers/modeltradearchive.cpp, src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/gui.pri, src/gui/ui/agreements.cpp, src/gui/ui/agreements.hpp, src/gui/ui/agreements.ui, src/gui/ui/dlgexportedcash.cpp, src/gui/ui/dlgmenu.cpp, src/gui/ui/dlgmenu.hpp, src/gui/ui/dlgmenu.ui, src/gui/ui/payments.cpp, src/gui/widgets/settings.cpp, src/gui/widgets/settings.hpp, src/gui/widgets/settings.ui
=> More stuff for recurring UI.

src/gui/widgets/settings.cpp, src/gui/widgets/settings.ui
=> BIP47 seed mnemonic in UI.

src/core/handlers/DBHandler.cpp, src/core/handlers/DBHandler.hpp, src/core/handlers/contacthandler.cpp, src/gui/ui/agreements.cpp, src/gui/widgets/contactdetails.cpp, src/gui/widgets/contactdetails.hpp, src/gui/widgets/nymdetails.cpp, src/gui/widgets/nymdetails.hpp, src/gui/widgets/settings.cpp
Claim verifications and Web of Trust, phase 1 finished in the UI.
=> Claim Verifications / Web of Trust done in UI

src/gui/widgets/contactdetails.cpp, src/gui/widgets/nymdetails.cpp, src/gui/widgets/pagenym_altlocation.cpp
=> Fixed bugs in Claim Verifications UI. Works now.

src/core/handlers/contacthandler.cpp, src/core/handlers/contacthandler.hpp, src/core/moneychanger.cpp, src/gui/widgets/contactdetails.cpp, src/gui/widgets/nymdetails.cpp, src/gui/widgets/pagenym_altlocation.cpp
Corresponds to: https://github.com/Open-Transactions/opentxs/pull/693
=> update for Identity API changes

src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/gui.pri, src/gui/widgets/homedetail.cpp, src/gui/widgets/homedetail.hpp, src/gui/widgets/nymdetails.cpp, src/gui/widgets/wizardconfirmsmartcontract.cpp, src/gui/widgets/wizardconfirmsmartcontract.hpp, src/gui/widgets/wizardconfirmsmartcontract.ui
=> Updates for smart contracts.

src/core/handlers/contacthandler.cpp, src/core/moneychanger.cpp, src/gui/widgets/nymdetails.cpp
=> Fixed build error on Mac.

src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/widgets/nymdetails.cpp, src/gui/widgets/serverdetails.cpp, src/rpc/mcrpcservice.cpp, src/rpc/mcrpcservice.h
https://github.com/Open-Transactions/opentxs/pull/733
=> Update for opentxs API changes

src/core/applicationmc.cpp, src/core/main.cpp
=> Fix for password callback.

src/core/moneychanger.cpp
=> Fix crash bug.

src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/widgets/settings.cpp, src/gui/widgets/settings.hpp, src/gui/widgets/settings.ui
=> Added manual pairing and socks5 proxy to settings

src/core/handlers/modelmessages.cpp, src/core/handlers/modelmessages.hpp, src/gui/ui/activity.cpp, src/gui/ui/activity.hpp, src/gui/ui/activity.ui, src/gui/widgets/accountdetails.cpp
=> Speed fixes for conversation details tab.

project/common.pri, project/moneychanger-qt/moneychanger-qt.pro, src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/ui/activity.cpp, src/gui/ui/activity.hpp, src/gui/ui/dlgoutbailment.cpp, src/gui/widgets/pagenym_altlocation.cpp, src/gui/widgets/pagenym_altlocation.hpp, src/gui/widgets/proposeplandlg.cpp, src/gui/widgets/settings.cpp, src/gui/widgets/settings.ui
Still need to finish out-bailment.
=> Pairing and in-bailment with new API.

src/gui/ui/activity.cpp, src/gui/ui/dlgoutbailment.cpp
=> Successful outbailment on Dash testnet.

src/core/main.cpp, src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/core/stable.hpp, src/gui/ui/activity.cpp, src/gui/ui/agreements.cpp, src/gui/ui/dlgdecrypt.cpp, src/gui/ui/dlgexportedcash.cpp, src/gui/ui/dlginbailment.cpp, src/gui/ui/dlgmenu.cpp, src/gui/ui/dlgpassphrasemanager.cpp, src/gui/ui/dlgtradearchive.cpp, src/gui/ui/messages.cpp, src/gui/ui/payments.cpp, src/gui/widgets/accountdetails.cpp, src/gui/widgets/agreementdetails.cpp, src/gui/widgets/assetdetails.cpp, src/gui/widgets/contactdetails.cpp, src/gui/widgets/homedetail.cpp, src/gui/widgets/nymdetails.cpp, src/gui/widgets/opentxscontactdetails.cpp, src/gui/widgets/pageoffer_accounts.cpp, src/gui/widgets/pagesmart_nymacct.cpp, src/gui/widgets/pagesmart_party.cpp, src/gui/widgets/pagesmart_partyacct.cpp, src/gui/widgets/proposeplandlg.cpp, src/gui/widgets/requestdlg.cpp, src/gui/widgets/serverdetails.cpp, src/gui/widgets/settings.cpp
Also, updated decryption dialog.
=> Updated import cash dlg. Groundwork for app rename.

src/core/handlers/DBHandler.cpp, src/core/handlers/DBHandler.hpp, src/gui/ui/activity.cpp, src/gui/ui/activity.hpp
=> QStandardItemModel replacing QSqlQQueryModel.

project/moneychanger-qt/moneychanger-qt.pro, src/core/applicationmc.cpp, src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/core/stable.hpp, src/gui/ui/activity.cpp, src/gui/ui/activity.hpp, src/gui/ui/activity.ui, src/gui/widgets/settings.ui
=> UI changes for Justus

src/core/moneychanger.cpp, src/core/network/Network.cpp, src/core/network/Network.h, src/gui/ui/activity.cpp, src/gui/widgets/proposeplandlg.cpp, src/gui/widgets/requestdlg.cpp, src/gui/widgets/requestdlg.hpp, src/gui/widgets/senddlg.cpp, src/gui/widgets/senddlg.hpp
I still have more to do, but I can merge this for now.
=> Updates to Send/Request to use Sync class

src/core/moneychanger.cpp, src/gui/widgets/requestdlg.cpp, src/gui/widgets/senddlg.cpp
=> Updated ‘Pay’ and ‘Request’ buttons to use new API

src/core/moneychanger.cpp, src/core/moneychanger.hpp
=> Pop-up message on notice of pending bailment.

src/gui/widgets/accountdetails.cpp, src/gui/widgets/assetdetails.cpp, src/gui/widgets/nymdetails.cpp
Signed-off-by: Stash User <guest@guest.austin.stashcrypto.net>
=> Changed ContactManager to use OTIdentifier for return values

src/core/handlers/contacthandler.cpp
=> Remove pre c++11 cruft

src/core/handlers/contacthandler.cpp, src/core/handlers/modelagreements.cpp, src/core/handlers/modelpayments.cpp, src/core/handlers/modelpayments.hpp, src/gui/ui/activity.cpp, src/gui/ui/activity.hpp, src/gui/ui/activity.ui, src/gui/ui/agreements.cpp, src/gui/ui/payments.cpp, src/gui/widgets/accountdetails.cpp
=> more changes ripping out recordlist

src/core/handlers/contacthandler.cpp, src/core/handlers/contacthandler.hpp, src/core/handlers/modelagreements.cpp, src/core/handlers/modelmessages.cpp, src/core/main.cpp, src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/ui/activity.cpp, src/gui/ui/agreements.cpp, src/gui/ui/dlgdecrypt.cpp, src/gui/ui/dlgencrypt.cpp, src/gui/ui/dlgmarkets.cpp, src/gui/ui/payments.cpp, src/gui/widgets/compose.cpp, src/gui/widgets/contactdetails.cpp, src/gui/widgets/credentials.cpp, src/gui/widgets/home.cpp, src/gui/widgets/homedetail.cpp, src/gui/widgets/nymdetails.cpp, src/gui/widgets/opentxscontactdetails.cpp, src/gui/widgets/proposeplandlg.cpp, src/gui/widgets/requestdlg.cpp, src/gui/widgets/senddlg.cpp
=> Strip out old Name Lookup code.

src/core/handlers/contacthandler.cpp, src/core/moneychanger.cpp, src/gui/ui/dlgdecrypt.cpp, src/gui/ui/dlgencrypt.cpp, src/gui/widgets/senddlg.cpp
=> Changed OTASCIIArmor to Armored, per new Opentxs.

src/core/main.cpp, src/core/passwordcallback.cpp, src/core/passwordcallback.hpp
=> Remove password callback GUI if opentxs has it off

src/core/handlers/modelpayments.cpp, src/core/moneychanger.cpp, src/core/moneychanger.hpp, src/gui/gui.pri, src/gui/ui/activity.cpp, src/gui/ui/agreements.cpp, src/gui/ui/dlgdecrypt.cpp, src/gui/ui/dlgencrypt.cpp, src/gui/ui/payments.cpp, src/gui/widgets/accountdetails.cpp, src/gui/widgets/agreementdetails.cpp, src/gui/widgets/cashpurse.cpp, src/gui/widgets/detailedit.cpp, src/gui/widgets/dlgchooser.cpp, src/gui/widgets/dlggetamount.cpp, src/gui/widgets/pagesmart_nymacct.cpp, src/gui/widgets/proposeplandlg.cpp, src/gui/widgets/requestdlg.cpp, src/gui/widgets/senddlg.cpp, src/gui/widgets/settings.cpp
=> Moneychanger now builds with latest opentxs.

src/core/handlers/DBHandler.cpp, src/core/moneychanger.cpp, src/gui/ui/activity.cpp, src/gui/widgets/compose.cpp
=> Fixes for Justus new API.
